services:
  scheduler:
    volumes:
      - ./dbt/workshop-vendas-dbt-airflow-2_data_warehouse/jornada_dw:/usr/local/airflow/dbt/jornada_dw
  dag-processor:
    volumes:
      - ./dbt/workshop-vendas-dbt-airflow-2_data_warehouse/jornada_dw:/usr/local/airflow/dbt/jornada_dw